/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNearbyRouteImport } from './routes/api/nearby'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated/sos'
import { Route as AuthenticatedSafetyRouteImport } from './routes/_authenticated/safety'
import { Route as AuthenticatedResponseTeamRouteImport } from './routes/_authenticated/response-team'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNearbyRouteImport } from './routes/_authenticated/nearby'
import { Route as AuthenticatedMyIncidentsRouteImport } from './routes/_authenticated/my-incidents'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'
import { Route as AuthenticatedResponderCasesRouteImport } from './routes/_authenticated/responder.cases'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTouristsRouteImport } from './routes/_authenticated/admin.tourists'
import { Route as AuthenticatedAdminSosRouteImport } from './routes/_authenticated/admin.sos'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNearbyRoute = ApiNearbyRouteImport.update({
  id: '/api/nearby',
  path: '/api/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyRoute = AuthenticatedSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponseTeamRoute =
  AuthenticatedResponseTeamRouteImport.update({
    id: '/response-team',
    path: '/response-team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNearbyRoute = AuthenticatedNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyIncidentsRoute =
  AuthenticatedMyIncidentsRouteImport.update({
    id: '/my-incidents',
    path: '/my-incidents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponderCasesRoute =
  AuthenticatedResponderCasesRouteImport.update({
    id: '/responder/cases',
    path: '/responder/cases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTouristsRoute =
  AuthenticatedAdminTouristsRouteImport.update({
    id: '/admin/tourists',
    path: '/admin/tourists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSosRoute = AuthenticatedAdminSosRouteImport.update({
  id: '/admin/sos',
  path: '/admin/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/my-incidents': typeof AuthenticatedMyIncidentsRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/response-team': typeof AuthenticatedResponseTeamRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/sos': typeof AuthenticatedSosRoute
  '/api/nearby': typeof ApiNearbyRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sos': typeof AuthenticatedAdminSosRoute
  '/admin/tourists': typeof AuthenticatedAdminTouristsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/responder/cases': typeof AuthenticatedResponderCasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/my-incidents': typeof AuthenticatedMyIncidentsRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/response-team': typeof AuthenticatedResponseTeamRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/sos': typeof AuthenticatedSosRoute
  '/api/nearby': typeof ApiNearbyRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sos': typeof AuthenticatedAdminSosRoute
  '/admin/tourists': typeof AuthenticatedAdminTouristsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/responder/cases': typeof AuthenticatedResponderCasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/my-incidents': typeof AuthenticatedMyIncidentsRoute
  '/_authenticated/nearby': typeof AuthenticatedNearbyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/response-team': typeof AuthenticatedResponseTeamRoute
  '/_authenticated/safety': typeof AuthenticatedSafetyRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/api/nearby': typeof ApiNearbyRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/sos': typeof AuthenticatedAdminSosRoute
  '/_authenticated/admin/tourists': typeof AuthenticatedAdminTouristsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/responder/cases': typeof AuthenticatedResponderCasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/register'
    | '/chatbot'
    | '/contacts'
    | '/dashboard'
    | '/feedback'
    | '/incidents'
    | '/my-incidents'
    | '/nearby'
    | '/profile'
    | '/report'
    | '/response-team'
    | '/safety'
    | '/sos'
    | '/api/nearby'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/sos'
    | '/admin/tourists'
    | '/admin/users'
    | '/responder/cases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/register'
    | '/chatbot'
    | '/contacts'
    | '/dashboard'
    | '/feedback'
    | '/incidents'
    | '/my-incidents'
    | '/nearby'
    | '/profile'
    | '/report'
    | '/response-team'
    | '/safety'
    | '/sos'
    | '/api/nearby'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/sos'
    | '/admin/tourists'
    | '/admin/users'
    | '/responder/cases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/register'
    | '/_authenticated/chatbot'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedback'
    | '/_authenticated/incidents'
    | '/_authenticated/my-incidents'
    | '/_authenticated/nearby'
    | '/_authenticated/profile'
    | '/_authenticated/report'
    | '/_authenticated/response-team'
    | '/_authenticated/safety'
    | '/_authenticated/sos'
    | '/api/nearby'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/sos'
    | '/_authenticated/admin/tourists'
    | '/_authenticated/admin/users'
    | '/_authenticated/responder/cases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegisterRoute: typeof RegisterRoute
  ApiNearbyRoute: typeof ApiNearbyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nearby': {
      id: '/api/nearby'
      path: '/api/nearby'
      fullPath: '/api/nearby'
      preLoaderRoute: typeof ApiNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety': {
      id: '/_authenticated/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AuthenticatedSafetyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/response-team': {
      id: '/_authenticated/response-team'
      path: '/response-team'
      fullPath: '/response-team'
      preLoaderRoute: typeof AuthenticatedResponseTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nearby': {
      id: '/_authenticated/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AuthenticatedNearbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-incidents': {
      id: '/_authenticated/my-incidents'
      path: '/my-incidents'
      fullPath: '/my-incidents'
      preLoaderRoute: typeof AuthenticatedMyIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/responder/cases': {
      id: '/_authenticated/responder/cases'
      path: '/responder/cases'
      fullPath: '/responder/cases'
      preLoaderRoute: typeof AuthenticatedResponderCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tourists': {
      id: '/_authenticated/admin/tourists'
      path: '/admin/tourists'
      fullPath: '/admin/tourists'
      preLoaderRoute: typeof AuthenticatedAdminTouristsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sos': {
      id: '/_authenticated/admin/sos'
      path: '/admin/sos'
      fullPath: '/admin/sos'
      preLoaderRoute: typeof AuthenticatedAdminSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedMyIncidentsRoute: typeof AuthenticatedMyIncidentsRoute
  AuthenticatedNearbyRoute: typeof AuthenticatedNearbyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedResponseTeamRoute: typeof AuthenticatedResponseTeamRoute
  AuthenticatedSafetyRoute: typeof AuthenticatedSafetyRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSosRoute: typeof AuthenticatedAdminSosRoute
  AuthenticatedAdminTouristsRoute: typeof AuthenticatedAdminTouristsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedResponderCasesRoute: typeof AuthenticatedResponderCasesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedMyIncidentsRoute: AuthenticatedMyIncidentsRoute,
  AuthenticatedNearbyRoute: AuthenticatedNearbyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedResponseTeamRoute: AuthenticatedResponseTeamRoute,
  AuthenticatedSafetyRoute: AuthenticatedSafetyRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSosRoute: AuthenticatedAdminSosRoute,
  AuthenticatedAdminTouristsRoute: AuthenticatedAdminTouristsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedResponderCasesRoute: AuthenticatedResponderCasesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RegisterRoute: RegisterRoute,
  ApiNearbyRoute: ApiNearbyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
